
let propertiesFonts = [
    'v-weight-normal',
    'v-weight-bold',
    'v-weight-100',
    'v-weight-200',
    'v-weight-300',
    'v-weight-400',
    'v-weight-500',
    'v-weight-600',
    'v-weight-700',
    'v-weight-800',
    'v-font-italic',
    'v-font-normal',
    'v-font-oblique',
    'v-font-sm',
    'v-font-md',
    'v-font-lg',
    'v-font-xl',
    'v-font-10',
    'v-font-12',
    'v-font-14',
    'v-font-16',
    'v-font-18',
    'v-font-20',
    'v-font-22',
    'v-font-24',
    'v-font-26',
    'v-font-28',
    'v-font-30',
    'v-font-32',
    'v-font-34',
    'v-font-36',
    'v-font-38',
    'v-font-40',
    'v-font-42',
    'v-font-44',
    'v-font-46',
    'v-font-48',
    'v-font-50',
    'v-font-52',
    'v-font-54',
    'v-font-56',
    'v-font-58',
    'v-font-60',
    'v-font-62',
    'v-font-64',
    'v-font-66',
    'v-font-68',
    'v-font-70',
]
let valuesFonts = [
    'font-weight: normal;',
    'font-weight: bold;',
    'font-weight: 100;',
    'font-weight: 200;',
    'font-weight: 300;',
    'font-weight: 400;',
    'font-weight: 500;',
    'font-weight: 600;',
    'font-weight: 700;',
    'font-weight: 800;',
    'font-style: italic;',
    'font-style: normal;',
    'font-style: oblique;',
    'font-size: 15px;',
    'font-size: 20px;',
    'font-size: 25px;',
    'font-size: 30px;',
    'font-size: 10px;',
    'font-size: 12px;',
    'font-size: 14px;',
    'font-size: 16px;',
    'font-size: 18px;',
    'font-size: 20px;',
    'font-size: 22px;',
    'font-size: 24px;',
    'font-size: 26px;',
    'font-size: 28px;',
    'font-size: 30px;',
    'font-size: 32px;',
    'font-size: 34px;',
    'font-size: 36px;',
    'font-size: 38px;',
    'font-size: 40px;',
    'font-size: 42px;',
    'font-size: 44px;',
    'font-size: 46px;',
    'font-size: 48px;',
    'font-size: 50px;',
    'font-size: 52px;',
    'font-size: 54px;',
    'font-size: 56px;',
    'font-size: 58px;',
    'font-size: 60px;',
    'font-size: 62px;',
    'font-size: 64px;',
    'font-size: 66px;',
    'font-size: 68px;',
    'font-size: 70px;',
]
for (var i = 0; i <= propertiesFonts.length; i++) {
    if (document.querySelector(`.${propertiesFonts[i]}`) && !document.querySelector('style').innerText.includes(propertiesFonts[i])) {
        let styles = ` 
            @media screen and (min-width: 900px) and (max-width: 1920px) {
                .${propertiesFonts[i]} { 
                    ${valuesFonts[i]}
                }
            }`;
        document.getElementsByTagName('style')[0].appendChild(document.createTextNode(styles));
    }
}
let propertiesFonts2 = [
    'mb:v-weight-normal',
    'mb:v-weight-bold',
    'mb:v-weight-100',
    'mb:v-weight-200',
    'mb:v-weight-300',
    'mb:v-weight-400',
    'mb:v-weight-500',
    'mb:v-weight-600',
    'mb:v-weight-700',
    'mb:v-weight-800',
    'mb:v-font-italic',
    'mb:v-font-normal',
    'mb:v-font-oblique',
    'mb:v-font-sm',
    'mb:v-font-md',
    'mb:v-font-lg',
    'mb:v-font-xl',
    'mb:v-font-10',
    'mb:v-font-12',
    'mb:v-font-14',
    'mb:v-font-16',
    'mb:v-font-18',
    'mb:v-font-20',
    'mb:v-font-22',
    'mb:v-font-24',
    'mb:v-font-26',
    'mb:v-font-28',
    'mb:v-font-30',
    'mb:v-font-32',
    'mb:v-font-34',
    'mb:v-font-36',
    'mb:v-font-38',
    'mb:v-font-40',
    'mb:v-font-42',
    'mb:v-font-44',
    'mb:v-font-46',
    'mb:v-font-48',
    'mb:v-font-50',
    'mb:v-font-52',
    'mb:v-font-54',
    'mb:v-font-56',
    'mb:v-font-58',
    'mb:v-font-60',
    'mb:v-font-62',
    'mb:v-font-64',
    'mb:v-font-66',
    'mb:v-font-68',
    'mb:v-font-70',
]
let valuesFonts2 = [
    'font-weight: normal;',
    'font-weight: bold;',
    'font-weight: 100;',
    'font-weight: 200;',
    'font-weight: 300;',
    'font-weight: 400;',
    'font-weight: 500;',
    'font-weight: 600;',
    'font-weight: 700;',
    'font-weight: 800;',
    'font-style: italic;',
    'font-style: normal;',
    'font-style: oblique;',
    'font-size: 15px;',
    'font-size: 20px;',
    'font-size: 25px;',
    'font-size: 30px;',
    'font-size: 10px;',
    'font-size: 12px;',
    'font-size: 14px;',
    'font-size: 16px;',
    'font-size: 18px;',
    'font-size: 20px;',
    'font-size: 22px;',
    'font-size: 24px;',
    'font-size: 26px;',
    'font-size: 28px;',
    'font-size: 30px;',
    'font-size: 32px;',
    'font-size: 34px;',
    'font-size: 36px;',
    'font-size: 38px;',
    'font-size: 40px;',
    'font-size: 42px;',
    'font-size: 44px;',
    'font-size: 46px;',
    'font-size: 48px;',
    'font-size: 50px;',
    'font-size: 52px;',
    'font-size: 54px;',
    'font-size: 56px;',
    'font-size: 58px;',
    'font-size: 60px;',
    'font-size: 62px;',
    'font-size: 64px;',
    'font-size: 66px;',
    'font-size: 68px;',
    'font-size: 70px;',
]
for (var i = 0; i <= propertiesFonts2.length; i++) {
    if (document.querySelector(`.${propertiesFonts2[i]}`) && !document.querySelector('style').innerText.includes(propertiesFonts2[i])) {
        let styles = ` 
            @media screen and (min-width: 320px) and (max-width: 600px){
                .${propertiesFonts2[i]} { 
                    ${valuesFonts2[i]}
                }
            }`;
        document.getElementsByTagName('style')[0].appendChild(document.createTextNode(styles));
    }
}
let propertiesFonts3 = [
    'tb:v-weight-normal',
    'tb:v-weight-bold',
    'tb:v-weight-100',
    'tb:v-weight-200',
    'tb:v-weight-300',
    'tb:v-weight-400',
    'tb:v-weight-500',
    'tb:v-weight-600',
    'tb:v-weight-700',
    'tb:v-weight-800',
    'tb:v-font-italic',
    'tb:v-font-normal',
    'tb:v-font-oblique',
    'tb:v-font-sm',
    'tb:v-font-md',
    'tb:v-font-lg',
    'tb:v-font-xl',
    'tb:v-font-10',
    'tb:v-font-12',
    'tb:v-font-14',
    'tb:v-font-16',
    'tb:v-font-18',
    'tb:v-font-20',
    'tb:v-font-22',
    'tb:v-font-24',
    'tb:v-font-26',
    'tb:v-font-28',
    'tb:v-font-30',
    'tb:v-font-32',
    'tb:v-font-34',
    'tb:v-font-36',
    'tb:v-font-38',
    'tb:v-font-40',
    'tb:v-font-42',
    'tb:v-font-44',
    'tb:v-font-46',
    'tb:v-font-48',
    'tb:v-font-50',
    'tb:v-font-52',
    'tb:v-font-54',
    'tb:v-font-56',
    'tb:v-font-58',
    'tb:v-font-60',
    'tb:v-font-62',
    'tb:v-font-64',
    'tb:v-font-66',
    'tb:v-font-68',
    'tb:v-font-70',
]
let valuesFonts3 = [
    'font-weight: normal;',
    'font-weight: bold;',
    'font-weight: 100;',
    'font-weight: 200;',
    'font-weight: 300;',
    'font-weight: 400;',
    'font-weight: 500;',
    'font-weight: 600;',
    'font-weight: 700;',
    'font-weight: 800;',
    'font-style: italic;',
    'font-style: normal;',
    'font-style: oblique;',
    'font-size: 15px;',
    'font-size: 20px;',
    'font-size: 25px;',
    'font-size: 30px;',
    'font-size: 10px;',
    'font-size: 12px;',
    'font-size: 14px;',
    'font-size: 16px;',
    'font-size: 18px;',
    'font-size: 20px;',
    'font-size: 22px;',
    'font-size: 24px;',
    'font-size: 26px;',
    'font-size: 28px;',
    'font-size: 30px;',
    'font-size: 32px;',
    'font-size: 34px;',
    'font-size: 36px;',
    'font-size: 38px;',
    'font-size: 40px;',
    'font-size: 42px;',
    'font-size: 44px;',
    'font-size: 46px;',
    'font-size: 48px;',
    'font-size: 50px;',
    'font-size: 52px;',
    'font-size: 54px;',
    'font-size: 56px;',
    'font-size: 58px;',
    'font-size: 60px;',
    'font-size: 62px;',
    'font-size: 64px;',
    'font-size: 66px;',
    'font-size: 68px;',
    'font-size: 70px;',
]
for (var i = 0; i <= propertiesFonts3.length; i++) {
    if (document.querySelector(`.${propertiesFonts3[i]}`) && !document.querySelector('style').innerText.includes(propertiesFonts3[i])) {
        let styles = ` 
            @media screen and (min-width: 600px) and (max-width: 900px){
                .${propertiesFonts3[i]} { 
                    ${valuesFonts3[i]}
                }
            }`;
        document.getElementsByTagName('style')[0].appendChild(document.createTextNode(styles));
    }
}
let propertiesFonts4 = [
    'pc:v-weight-normal',
    'pc:v-weight-bold',
    'pc:v-weight-100',
    'pc:v-weight-200',
    'pc:v-weight-300',
    'pc:v-weight-400',
    'pc:v-weight-500',
    'pc:v-weight-600',
    'pc:v-weight-700',
    'pc:v-weight-800',
    'pc:v-font-italic',
    'pc:v-font-normal',
    'pc:v-font-oblique',
    'pc:v-font-sm',
    'pc:v-font-md',
    'pc:v-font-lg',
    'pc:v-font-xl',
    'pc:v-font-10',
    'pc:v-font-12',
    'pc:v-font-14',
    'pc:v-font-16',
    'pc:v-font-18',
    'pc:v-font-20',
    'pc:v-font-22',
    'pc:v-font-24',
    'pc:v-font-26',
    'pc:v-font-28',
    'pc:v-font-30',
    'pc:v-font-32',
    'pc:v-font-34',
    'pc:v-font-36',
    'pc:v-font-38',
    'pc:v-font-40',
    'pc:v-font-42',
    'pc:v-font-44',
    'pc:v-font-46',
    'pc:v-font-48',
    'pc:v-font-50',
    'pc:v-font-52',
    'pc:v-font-54',
    'pc:v-font-56',
    'pc:v-font-58',
    'pc:v-font-60',
    'pc:v-font-62',
    'pc:v-font-64',
    'pc:v-font-66',
    'pc:v-font-68',
    'pc:v-font-70',
]
let valuesFonts4 = [
    'font-weight: normal;',
    'font-weight: bold;',
    'font-weight: 100;',
    'font-weight: 200;',
    'font-weight: 300;',
    'font-weight: 400;',
    'font-weight: 500;',
    'font-weight: 600;',
    'font-weight: 700;',
    'font-weight: 800;',
    'font-style: italic;',
    'font-style: normal;',
    'font-style: oblique;',
    'font-size: 15px;',
    'font-size: 20px;',
    'font-size: 25px;',
    'font-size: 30px;',
    'font-size: 10px;',
    'font-size: 12px;',
    'font-size: 14px;',
    'font-size: 16px;',
    'font-size: 18px;',
    'font-size: 20px;',
    'font-size: 22px;',
    'font-size: 24px;',
    'font-size: 26px;',
    'font-size: 28px;',
    'font-size: 30px;',
    'font-size: 32px;',
    'font-size: 34px;',
    'font-size: 36px;',
    'font-size: 38px;',
    'font-size: 40px;',
    'font-size: 42px;',
    'font-size: 44px;',
    'font-size: 46px;',
    'font-size: 48px;',
    'font-size: 50px;',
    'font-size: 52px;',
    'font-size: 54px;',
    'font-size: 56px;',
    'font-size: 58px;',
    'font-size: 60px;',
    'font-size: 62px;',
    'font-size: 64px;',
    'font-size: 66px;',
    'font-size: 68px;',
    'font-size: 70px;',
]
for (var i = 0; i <= propertiesFonts4.length; i++) {
    if (document.querySelector(`.${propertiesFonts4[i]}`) && !document.querySelector('style').innerText.includes(propertiesFonts4[i])) {
        let styles = ` 
            @media screen and (min-width: 1920px){
                .${propertiesFonts4[i]} { 
                    ${valuesFonts4[i]}
                }
            }`;
        document.getElementsByTagName('style')[0].appendChild(document.createTextNode(styles));
    }
}