let nameIcons = [
    'v-home-icon',
    'v-cog-icon',
    'v-car-icon',
    'v-chart-line-icon',
    'v-thumbs-up-icon',
    'v-mobile-icon',
    'v-laptop-icon',
    'v-desktop-icon',
    'v-bars-icon',
    'v-comments-icon',
    'v-tachometer-alt-icon',
    'v-rocket-icon',
    'v-bell-icon',
    'v-table-icon',
    'v-pen-icon',
    'v-thumbtack-icon',
    'v-trophy-icon',
    'v-modal-icon',
    'v-calendar-alt-icon',
    'v-chart-pie-icon',
    'v-map-marked-alt-icon',
    'v-dollar-signin-icon',
    'v-plus-circle-icon',
    'v-search-icon',
    'v-folder-plus-icon',
    'v-cart-plus-icon',
    'v-envelope-icon',
    'v-paper-plane-icon',
    'v-smile-icon',
    'v-star-icon',
    'v-facebook-icon',
    'v-whatsapp-icon',
    'v-instagram-icon',
    'v-discord-icon',
    'v-github-icon',
    'v-youtube-icon',
    'v-dribbble-icon',
    'v-behance-icon',
    'v-figma-icon',
    'v-undo-alt-icon',
    'v-share-icon',
    'v-sign-out-icon',
    'v-sign-in-icon',
    'v-keyboard-icon',
    'v-key-icon',
    'v-backspace-icon',
    'v-trash-icon',
    'v-moon-icon',
    'v-lightbulb-icon',
    'v-comment-icon',
    'v-icons-icon',
    'v-wrench-icon',
    'v-utensils-icon',
    'v-hamburger-icon',
    'v-brain-icon',
    'v-align-left-icon',
    'v-address-card-icon',
    'v-angle-down-icon',
    'v-angle-up-icon',
    'v-angle-left-icon',
    'v-angle-right-icon',
    'v-arrow-down-icon',
    'v-arrow-up-icon',
    'v-arrow-left-icon',
    'v-arrow-right-icon',
    'v-hospital-icon',
    'v-hotel-icon',
    'v-stethoscope-icon',
    'v-tablets-icon',
    'v-capsules-icon',
    'v-prescription-bottle-icon',
    'v-cloud-upload-icon',
    'v-cloud-download-icon',
    'v-cloud-showers-heavy-icon',
    'v-cloud-sun-icon',
    'v-cloud-moon-icon',
    'v-flag-icon',
    'v-volume-up-icon',
    'v-html5-icon',
    'v-css3-icon',
    'v-js-icon',
    'v-react-icon',
    'v-laravel-icon',
    'v-node-icon',
    'v-python-icon',
    'v-android-icon',
    'v-apple-icon',
    'v-hourglass-icon',
    'v-skull-crossbones-icon',
    'v-crown-icon',
    'v-compas-icon',
    'v-coffee-icon',
    'v-crosshairs-icon',
    'v-eye-icon',
    'v-globe-asia-icon',
    'v-gem-icon',
    'v-book-icon',
    'v-object-ungroup-icon',
    'v-truck-icon',
    'v-tree-icon',
    'v-plane-icon',
    'v-traffic-light-icon',
    'v-tv-icon',
    'v-tty-icon',
    'v-toggle-on-icon',
    'v-tint-icon',
    'v-twitter-icon',
    'v-tired-icon',
    'v-times-circle-icon',
    'v-times-icon',
    'v-tiktok-icon',
    'v-toilet-paper-icon',
    'v-toilet-icon',
    'v-tshirt-icon',
    'v-twitch-icon',
    'v-bolt-icon',
    'v-algolia-icon',
    'v-ambulance-icon',
]
let valueIcons = [
    "fas fa-home",
    "fas fa-cog",
    "fas fa-car",
    "fas fa-chart-line",
    "fas fa-thumbs-up",
    "fas fa-mobile",
    "fas fa-laptop",
    "fas fa-desktop",
    "fas fa-bars",
    "fas fa-comments",
    "fas fa-tachometer-alt",
    "fas fa-rocket",
    "fas fa-bell",
    "fas fa-table",
    "fas fa-pen",
    "fas fa-thumbtack",
    "fas fa-trophy",
    "fas fa-medal",
    "fas fa-calendar-alt",
    "fas fa-chart-pie",
    "fas fa-map-marked-alt",
    "fas fa-dollar-sign",
    "fas fa-plus-circle",
    "fas fa-search",
    "fas fa-folder-plus",
    "fas fa-cart-plus",
    "fas fa-envelope",
    "fas fa-paper-plane",
    "fas fa-smile",
    "fas fa-star",
    "fab fa-facebook",
    "fab fa-whatsapp",
    "fab fa-instagram",
    "fab fa-discord",
    "fab fa-github",
    "fab fa-youtube",
    "fab fa-dribbble",
    "fab fa-behance",
    "fab fa-figma",
    "fas fa-undo-alt",
    "fas fa-share",
    "fas fa-sign-out-alt",
    "fas fa-sign-in-alt",
    "fas fa-keyboard",
    "fas fa-key",
    "fas fa-backspace",
    "fas fa-trash",
    "fas fa-moon",
    "fas fa-lightbulb",
    "fas fa-comment",
    "fas fa-icons",
    "fas fa-wrench",
    "fas fa-utensils",
    "fas fa-hamburger",
    "fas fa-brain",
    "fas fa-align-left",
    "fas fa-address-card",
    "fas fa-angle-down",
    "fas fa-angle-up",
    "fas fa-angle-left",
    "fas fa-angle-right",
    "fas fa-arrow-down",
    "fas fa-arrow-up",
    "fas fa-arrow-left",
    "fas fa-arrow-right",
    "fas fa-hospital",
    "fas fa-hotel",
    "fas fa-stethoscope",
    "fas fa-tablets",
    "fas fa-capsules",
    "fas fa-prescription-bottle-alt",
    "fas fa-cloud-upload-alt",
    "fas fa-cloud-download-alt",
    "fas fa-cloud-showers-heavy",
    "fas fa-cloud-sun",
    "fas fa-cloud-moon",
    "fas fa-flag",
    "fas fa-volume-up",
    "fab fa-html5",
    "fab fa-css3",
    "fab fa-js",
    "fab fa-react",
    "fab fa-laravel",
    "fab fa-node",
    "fab fa-python",
    "fab fa-android",
    "fab fa-apple",
    "fas fa-hourglass",
    "fas fa-skull-crossbones",
    "fas fa-crown",
    "fas fa-compass",
    "fas fa-coffee",
    "fas fa-crosshairs",
    "fas fa-eye",
    "fas fa-globe-asia",
    "fas fa-gem",
    "fas fa-book",
    "fas fa-object-ungroup",
    "fas fa-truck",
    "fas fa-tree",
    "fas fa-plane",
    "fas fa-traffic-light",
    "fas fa-tv",
    "fas fa-tty",
    "fas fa-toggle-on",
    "fas fa-tint",
    "fab fa-twitter",
    "fas fa-tired",
    "fas fa-times-circle",
    "fas fa-times",
    "fab fa-tiktok",
    "fas fa-toilet-paper",
    "fas fa-toilet",
    "fas fa-tshirt",
    "fab fa-twitch",
    "fas fa-bolt",
    "fab fa-algolia",
    "fas fa-ambulance",
]

for (let i = 0; i <= nameIcons.length; i++) {
    
    let element = document.getElementsByClassName(`${nameIcons[i]}`);
    
    for(let x = 0; x < element.length; x++) {
        console.log('ok :',element)
        if (document.getElementsByClassName(`${nameIcons[i]}`)) {
            element[x].className = element[x].className.replace(`${nameIcons[i]}`, `${valueIcons[i]}`);
        }
    }
   

for (let i = 0; i <= nameIcons.length - 1; i++) {
    
    if (document.querySelector(`.${nameIcons[i]}`)) {
        document.querySelector(`.${nameIcons[i]}`).className = document.querySelector(`.${nameIcons[i]}`).className.replace(`${nameIcons[i]}`, `${valueIcons[i]}`);
    }
}
}