let propertiesMargins = [
    'v-m-auto',
    'v-m-0px',
    'v-m-5px',
    'v-m-10px',
    'v-m-15px',
    'v-m-20px',
    'v-m-25px',
    'v-m-30px',
    'v-m-35px',
    'v-m-40px',
    'v-m-45px',
    'v-m-50px',
    'v-m-55px',
    'v-m-60px',
    'v-m-65px',
    'v-m-70px',
    'v-m-75px',
    'v-m-80px',
    'v-m-85px',
    'v-m-90px',
    'v-m-95px',
    'v-m-100px',
    'v-m-200px',
    'v-m-300px',
    'v-m-400px',
    'v-m-500px',
    'v-m-600px',
    'v-m-700px',
    'v-m-800px',
    'v-mt-auto',
    'v-mt-0px',
    'v-mt-5px',
    'v-mt-10px',
    'v-mt-15px',
    'v-mt-20px',
    'v-mt-25px',
    'v-mt-30px',
    'v-mt-35px',
    'v-mt-40px',
    'v-mt-45px',
    'v-mt-50px',
    'v-mt-55px',
    'v-mt-60px',
    'v-mt-65px',
    'v-mt-70px',
    'v-mt-75px',
    'v-mt-80px',
    'v-mt-85px',
    'v-mt-90px',
    'v-mt-95px',
    'v-mt-100px',
    'v-mt-200px',
    'v-mt-300px',
    'v-mt-400px',
    'v-mt-500px',
    'v-mt-600px',
    'v-mt-700px',
    'v-mt-800px',
    'v-ml-auto',
    'v-ml-0px',
    'v-ml-5px',
    'v-ml-10px',
    'v-ml-15px',
    'v-ml-20px',
    'v-ml-25px',
    'v-ml-30px',
    'v-ml-35px',
    'v-ml-40px',
    'v-ml-45px',
    'v-ml-50px',
    'v-ml-55px',
    'v-ml-60px',
    'v-ml-65px',
    'v-ml-70px',
    'v-ml-75px',
    'v-ml-80px',
    'v-ml-85px',
    'v-ml-90px',
    'v-ml-95px',
    'v-ml-100px',
    'v-ml-200px',
    'v-ml-300px',
    'v-ml-400px',
    'v-ml-500px',
    'v-ml-600px',
    'v-ml-700px',
    'v-ml-800px',
    'v-mr-auto',
    'v-mr-0px',
    'v-mr-5px',
    'v-mr-10px',
    'v-mr-15px',
    'v-mr-20px',
    'v-mr-25px',
    'v-mr-30px',
    'v-mr-35px',
    'v-mr-40px',
    'v-mr-45px',
    'v-mr-50px',
    'v-mr-55px',
    'v-mr-60px',
    'v-mr-65px',
    'v-mr-70px',
    'v-mr-75px',
    'v-mr-80px',
    'v-mr-85px',
    'v-mr-90px',
    'v-mr-95px',
    'v-mr-100px',
    'v-mr-200px',
    'v-mr-300px',
    'v-mr-400px',
    'v-mr-500px',
    'v-mr-600px',
    'v-mr-700px',
    'v-mr-800px',
    'v-mb-auto',
    'v-mb-0px',
    'v-mb-5px',
    'v-mb-10px',
    'v-mb-15px',
    'v-mb-20px',
    'v-mb-25px',
    'v-mb-30px',
    'v-mb-35px',
    'v-mb-40px',
    'v-mb-45px',
    'v-mb-50px',
    'v-mb-55px',
    'v-mb-60px',
    'v-mb-65px',
    'v-mb-70px',
    'v-mb-75px',
    'v-mb-80px',
    'v-mb-85px',
    'v-mb-90px',
    'v-mb-95px',
    'v-mb-100px',
    'v-mb-200px',
    'v-mb-300px',
    'v-mb-400px',
    'v-mb-500px',
    'v-mb-600px',
    'v-mb-700px',
    'v-mb-800px',
]
let valuesMargins = [
    'margin: auto;',
    'margin: 0px;',
    'margin: 5px;',
    'margin: 10px;',
    'margin: 15px;',
    'margin: 20px;',
    'margin: 25px;',
    'margin: 30px;',
    'margin: 35px;',
    'margin: 40px;',
    'margin: 45px;',
    'margin: 50px;',
    'margin: 55px;',
    'margin: 60px;',
    'margin: 65px;',
    'margin: 70px;',
    'margin: 75px;',
    'margin: 80px;',
    'margin: 85px;',
    'margin: 90px;',
    'margin: 95px;',
    'margin: 100px;',
    'margin: 200px;',
    'margin: 300px;',
    'margin: 400px;',
    'margin: 500px;',
    'margin: 600px;',
    'margin: 700px;',
    'margin: 800px;',
    'margin-top: auto;',
    'margin-top: 0px;',
    'margin-top: 5px;',
    'margin-top: 10px;',
    'margin-top: 15px;',
    'margin-top: 20px;',
    'margin-top: 25px;',
    'margin-top: 30px;',
    'margin-top: 35px;',
    'margin-top: 40px;',
    'margin-top: 45px;',
    'margin-top: 50px;',
    'margin-top: 55px;',
    'margin-top: 60px;',
    'margin-top: 65px;',
    'margin-top: 70px;',
    'margin-top: 75px;',
    'margin-top: 80px;',
    'margin-top: 85px;',
    'margin-top: 90px;',
    'margin-top: 95px;',
    'margin-top: 100px;',
    'margin-top: 200px;',
    'margin-top: 300px;',
    'margin-top: 400px;',
    'margin-top: 500px;',
    'margin-top: 600px;',
    'margin-top: 700px;',
    'margin-top: 800px;',
    'margin-left: auto;',
    'margin-left: 0px;',
    'margin-left: 5px;',
    'margin-left: 10px;',
    'margin-left: 15px;',
    'margin-left: 20px;',
    'margin-left: 25px;',
    'margin-left: 30px;',
    'margin-left: 35px;',
    'margin-left: 40px;',
    'margin-left: 45px;',
    'margin-left: 50px;',
    'margin-left: 55px;',
    'margin-left: 60px;',
    'margin-left: 65px;',
    'margin-left: 70px;',
    'margin-left: 75px;',
    'margin-left: 80px;',
    'margin-left: 85px;',
    'margin-left: 90px;',
    'margin-left: 95px;',
    'margin-left: 100px;',
    'margin-left: 200px;',
    'margin-left: 300px;',
    'margin-left: 400px;',
    'margin-left: 500px;',
    'margin-left: 600px;',
    'margin-left: 700px;',
    'margin-left: 800px;',
    'margin-right: auto;',
    'margin-right: 0px;',
    'margin-right: 5px;',
    'margin-right: 10px;',
    'margin-right: 15px;',
    'margin-right: 20px;',
    'margin-right: 25px;',
    'margin-right: 30px;',
    'margin-right: 35px;',
    'margin-right: 40px;',
    'margin-right: 45px;',
    'margin-right: 50px;',
    'margin-right: 55px;',
    'margin-right: 60px;',
    'margin-right: 65px;',
    'margin-right: 70px;',
    'margin-right: 75px;',
    'margin-right: 80px;',
    'margin-right: 85px;',
    'margin-right: 90px;',
    'margin-right: 95px;',
    'margin-right: 100px;',
    'margin-right: 200px;',
    'margin-right: 300px;',
    'margin-right: 400px;',
    'margin-right: 500px;',
    'margin-right: 600px;',
    'margin-right: 700px;',
    'margin-right: 800px;',
    'margin-bottom: auto;',
    'margin-bottom: 0px;',
    'margin-bottom: 5px;',
    'margin-bottom: 10px;',
    'margin-bottom: 15px;',
    'margin-bottom: 20px;',
    'margin-bottom: 25px;',
    'margin-bottom: 30px;',
    'margin-bottom: 35px;',
    'margin-bottom: 40px;',
    'margin-bottom: 45px;',
    'margin-bottom: 50px;',
    'margin-bottom: 55px;',
    'margin-bottom: 60px;',
    'margin-bottom: 65px;',
    'margin-bottom: 70px;',
    'margin-bottom: 75px;',
    'margin-bottom: 80px;',
    'margin-bottom: 85px;',
    'margin-bottom: 90px;',
    'margin-bottom: 95px;',
    'margin-bottom: 100px;',
    'margin-bottom: 200px;',
    'margin-bottom: 300px;',
    'margin-bottom: 400px;',
    'margin-bottom: 500px;',
    'margin-bottom: 600px;',
    'margin-bottom: 700px;',
    'margin-bottom: 800px;',
];
for (var i = 0; i <= propertiesMargins.length; i++) {
    if (document.querySelector(`.${propertiesMargins[i]}`) && !document.querySelector('style').innerText.includes(propertiesMargins[i])) {
        let styles = ` 
        @media screen and (min-width: 900px){
            .${propertiesMargins[i]} { 
                ${valuesMargins[i]}
            }
        }`;
        document.getElementsByTagName('style')[0].appendChild(document.createTextNode(styles));
    }
}
