let propertiesPadding = [
    'v-p-auto',
    'v-p-0px',
    'v-p-5px',
    'v-p-10px',
    'v-p-15px',
    'v-p-20px',
    'v-p-25px',
    'v-p-30px',
    'v-p-35px',
    'v-p-40px',
    'v-p-45px',
    'v-p-50px',
    'v-p-55px',
    'v-p-60px',
    'v-p-65px',
    'v-p-70px',
    'v-p-75px',
    'v-p-80px',
    'v-p-85px',
    'v-p-90px',
    'v-p-95px',
    'v-p-100px',
    'v-p-200px',
    'v-p-300px',
    'v-p-400px',
    'v-p-500px',
    'v-p-600px',
    'v-p-700px',
    'v-p-800px',
    'v-pt-auto',
    'v-pt-0px',
    'v-pt-5px',
    'v-pt-10px',
    'v-pt-15px',
    'v-pt-20px',
    'v-pt-25px',
    'v-pt-30px',
    'v-pt-35px',
    'v-pt-40px',
    'v-pt-45px',
    'v-pt-50px',
    'v-pt-55px',
    'v-pt-60px',
    'v-pt-65px',
    'v-pt-70px',
    'v-pt-75px',
    'v-pt-80px',
    'v-pt-85px',
    'v-pt-90px',
    'v-pt-95px',
    'v-pt-100px',
    'v-pt-200px',
    'v-pt-300px',
    'v-pt-400px',
    'v-pt-500px',
    'v-pt-600px',
    'v-pt-700px',
    'v-pt-800px',
    'v-pl-auto',
    'v-pl-0px',
    'v-pl-5px',
    'v-pl-10px',
    'v-pl-15px',
    'v-pl-20px',
    'v-pl-25px',
    'v-pl-30px',
    'v-pl-35px',
    'v-pl-40px',
    'v-pl-45px',
    'v-pl-50px',
    'v-pl-55px',
    'v-pl-60px',
    'v-pl-65px',
    'v-pl-70px',
    'v-pl-75px',
    'v-pl-80px',
    'v-pl-85px',
    'v-pl-90px',
    'v-pl-95px',
    'v-pl-100px',
    'v-pl-200px',
    'v-pl-300px',
    'v-pl-400px',
    'v-pl-500px',
    'v-pl-600px',
    'v-pl-700px',
    'v-pl-800px',
    'v-pr-auto',
    'v-pr-0px',
    'v-pr-5px',
    'v-pr-10px',
    'v-pr-15px',
    'v-pr-20px',
    'v-pr-25px',
    'v-pr-30px',
    'v-pr-35px',
    'v-pr-40px',
    'v-pr-45px',
    'v-pr-50px',
    'v-pr-55px',
    'v-pr-60px',
    'v-pr-65px',
    'v-pr-70px',
    'v-pr-75px',
    'v-pr-80px',
    'v-pr-85px',
    'v-pr-90px',
    'v-pr-95px',
    'v-pr-100px',
    'v-pr-200px',
    'v-pr-300px',
    'v-pr-400px',
    'v-pr-500px',
    'v-pr-600px',
    'v-pr-700px',
    'v-pr-800px',
    'v-pb-auto',
    'v-pb-0px',
    'v-pb-5px',
    'v-pb-10px',
    'v-pb-15px',
    'v-pb-20px',
    'v-pb-25px',
    'v-pb-30px',
    'v-pb-35px',
    'v-pb-40px',
    'v-pb-45px',
    'v-pb-50px',
    'v-pb-55px',
    'v-pb-60px',
    'v-pb-65px',
    'v-pb-70px',
    'v-pb-75px',
    'v-pb-80px',
    'v-pb-85px',
    'v-pb-90px',
    'v-pb-95px',
    'v-pb-100px',
    'v-pb-200px',
    'v-pb-300px',
    'v-pb-400px',
    'v-pb-500px',
    'v-pb-600px',
    'v-pb-700px',
    'v-pb-800px',
]
let valuesPadding = [
    'padding: auto;',
    'padding: 0px;',
    'padding: 5px;',
    'padding: 10px;',
    'padding: 15px;',
    'padding: 20px;',
    'padding: 25px;',
    'padding: 30px;',
    'padding: 35px;',
    'padding: 40px;',
    'padding: 45px;',
    'padding: 50px;',
    'padding: 55px;',
    'padding: 60px;',
    'padding: 65px;',
    'padding: 70px;',
    'padding: 75px;',
    'padding: 80px;',
    'padding: 85px;',
    'padding: 90px;',
    'padding: 95px;',
    'padding: 100px;',
    'padding: 200px;',
    'padding: 300px;',
    'padding: 400px;',
    'padding: 500px;',
    'padding: 600px;',
    'padding: 700px;',
    'padding: 800px;',
    'padding-top: auto;',
    'padding-top: 0px;',
    'padding-top: 5px;',
    'padding-top: 10px;',
    'padding-top: 15px;',
    'padding-top: 20px;',
    'padding-top: 25px;',
    'padding-top: 30px;',
    'padding-top: 35px;',
    'padding-top: 40px;',
    'padding-top: 45px;',
    'padding-top: 50px;',
    'padding-top: 55px;',
    'padding-top: 60px;',
    'padding-top: 65px;',
    'padding-top: 70px;',
    'padding-top: 75px;',
    'padding-top: 80px;',
    'padding-top: 85px;',
    'padding-top: 90px;',
    'padding-top: 95px;',
    'padding-top: 100px;',
    'padding-top: 200px;',
    'padding-top: 300px;',
    'padding-top: 400px;',
    'padding-top: 500px;',
    'padding-top: 600px;',
    'padding-top: 700px;',
    'padding-top: 800px;',
    'padding-left: auto;',
    'padding-left: 0px;',
    'padding-left: 5px;',
    'padding-left: 10px;',
    'padding-left: 15px;',
    'padding-left: 20px;',
    'padding-left: 25px;',
    'padding-left: 30px;',
    'padding-left: 35px;',
    'padding-left: 40px;',
    'padding-left: 45px;',
    'padding-left: 50px;',
    'padding-left: 55px;',
    'padding-left: 60px;',
    'padding-left: 65px;',
    'padding-left: 70px;',
    'padding-left: 75px;',
    'padding-left: 80px;',
    'padding-left: 85px;',
    'padding-left: 90px;',
    'padding-left: 95px;',
    'padding-left: 100px;',
    'padding-left: 200px;',
    'padding-left: 300px;',
    'padding-left: 400px;',
    'padding-left: 500px;',
    'padding-left: 600px;',
    'padding-left: 700px;',
    'padding-left: 800px;',
    'padding-right: auto;',
    'padding-right: 0px;',
    'padding-right: 5px;',
    'padding-right: 10px;',
    'padding-right: 15px;',
    'padding-right: 20px;',
    'padding-right: 25px;',
    'padding-right: 30px;',
    'padding-right: 35px;',
    'padding-right: 40px;',
    'padding-right: 45px;',
    'padding-right: 50px;',
    'padding-right: 55px;',
    'padding-right: 60px;',
    'padding-right: 65px;',
    'padding-right: 70px;',
    'padding-right: 75px;',
    'padding-right: 80px;',
    'padding-right: 85px;',
    'padding-right: 90px;',
    'padding-right: 95px;',
    'padding-right: 100px;',
    'padding-right: 200px;',
    'padding-right: 300px;',
    'padding-right: 400px;',
    'padding-right: 500px;',
    'padding-right: 600px;',
    'padding-right: 700px;',
    'padding-right: 800px;',
    'padding-bottom: auto;',
    'padding-bottom: 0px;',
    'padding-bottom: 5px;',
    'padding-bottom: 10px;',
    'padding-bottom: 15px;',
    'padding-bottom: 20px;',
    'padding-bottom: 25px;',
    'padding-bottom: 30px;',
    'padding-bottom: 35px;',
    'padding-bottom: 40px;',
    'padding-bottom: 45px;',
    'padding-bottom: 50px;',
    'padding-bottom: 55px;',
    'padding-bottom: 60px;',
    'padding-bottom: 65px;',
    'padding-bottom: 70px;',
    'padding-bottom: 75px;',
    'padding-bottom: 80px;',
    'padding-bottom: 85px;',
    'padding-bottom: 90px;',
    'padding-bottom: 95px;',
    'padding-bottom: 100px;',
    'padding-bottom: 200px;',
    'padding-bottom: 300px;',
    'padding-bottom: 400px;',
    'padding-bottom: 500px;',
    'padding-bottom: 600px;',
    'padding-bottom: 700px;',
    'padding-bottom: 800px;',
]
for (var i = 0; i <= propertiesPadding.length; i++) {
    if (document.querySelector(`.${propertiesPadding[i]}`) && !document.querySelector('style').innerText.includes(propertiesPadding[i])) {
        let styles = `  
        @media screen and (min-width: 900px){
            .${propertiesPadding[i]} { 
                ${valuesPadding[i]}
            }
        }`;
        document.getElementsByTagName('style')[0].appendChild(document.createTextNode(styles));
    }
}
