let propertiesTransform = [
    'v-rotate-0',
    'v-rotate-30',
    'v-rotate-45',
    'v-rotate-90',
    'v-rotate-120',
    'v-rotate-180',
    'v-rotate-360',
    'v-scale--1',
    'v-scale--2',
    'v-scale--3',
    'v-scale--4',
    'v-scale--5',
    'v-scale--6',
    'v-scale--7',
    'v-scale--8',
    'v-scale--9',
    'v-scale-1',
    'v-scale-2',
    'v-scale-3',
    'v-scale-4',
    'v-skew-1',
    'v-skew-2',
    'v-skew-3',
    'v-skew-4',
    '-v-skew-1',
    '-v-skew-2',
    '-v-skew-3',
    '-v-skew-4',
    'v-translate-1',
    'v-translate-2',
    'v-translate-3',
    'v-translate-4',
    'v-translate-middle',
    '-v-translate-1',
    '-v-translate-2',
    '-v-translate-3',
    '-v-translate-4',
    '-v-translate-middle',
    'v-translateX-1',
    'v-translateX-2',
    'v-translateX-3',
    'v-translateX-4',
    'v-translateX-middle',
    '-v-translateX-1',
    '-v-translateX-2',
    '-v-translateX-3',
    '-v-translateX-4',
    '-v-translateX-middle',
    'v-translateY-1',
    'v-translateY-2',
    'v-translateY-3',
    'v-translateY-4',
    'v-translateY-middle',
    '-v-translateY-1',
    '-v-translateY-2',
    '-v-translateY-3',
    '-v-translateY-4',
    '-v-translateY-middle',
    'v-translateZ-1',
    'v-translateZ-2',
    'v-translateZ-3',
    'v-translateZ-4',
    'v-translateZ-middle',
    '-v-translateZ-1',
    '-v-translateZ-2',
    '-v-translateZ-3',
    '-v-translateZ-4',
    '-v-translateZ-middle'
]
let valuesTransform = [
  'transform: rotate(0deg)',
  'transform: rotate(30deg)',
  'transform: rotate(45deg)',
  'transform: rotate(90deg)',
  'transform: rotate(120deg)',
  'transform: rotate(180deg)',
  'transform: rotate(360deg)',
  'transform: scale(0.1)',
  'transform: scale(0.2)',
  'transform: scale(0.3)',
  'transform: scale(0.4)',
  'transform: scale(0.5)',
  'transform: scale(0.6)',
  'transform: scale(0.7)',
  'transform: scale(0.8)',
  'transform: scale(0.9)',
  'transform: scale(1)',
  'transform: scale(2)',
  'transform: scale(3)',
  'transform: scale(4)',
  'transform: skew(5deg)',
  'transform: skew(10deg)',
  'transform: skew(15deg)',
  'transform: skew(20deg)',
  'transform: skew(-5deg)',
  'transform: skew(-10deg)',
  'transform: skew(-15deg)',
  'transform: skew(-20deg)',
  'transform: translate(10%)',
  'transform: translate(20%)',
  'transform: translate(30%)',
  'transform: translate(40%)',
  'transform: translate(50%)',
  'transform: translate(-10%)',
  'transform: translate(-20%)',
  'transform: translate(-30%)',
  'transform: translate(-40%)',
  'transform: translate(-50%)',
  'transform: translateX(10%)',
  'transform: translateX(20%)',
  'transform: translateX(30%)',
  'transform: translateX(40%)',
  'transform: translateX(50%)',
  'transform: translateX(-10%)',
  'transform: translateX(-20%)',
  'transform: translateX(-30%)',
  'transform: translateX(-40%)',
  'transform: translateX(-50%)',
  'transform: translateY(10%)',
  'transform: translateY(20%)',
  'transform: translateY(30%)',
  'transform: translateY(40%)',
  'transform: translateY(50%)',
  'transform: translateY(-10%)',
  'transform: translateY(-20%)',
  'transform: translateY(-30%)',
  'transform: translateY(-40%)',
  'transform: translateY(-50%)',
  'transform: translateZ(10%)',
  'transform: translateZ(20%)',
  'transform: translateZ(30%)',
  'transform: translateZ(40%)',
  'transform: translateZ(50%)',
  'transform: translateZ(-10%)',
  'transform: translateZ(-20%)',
  'transform: translateZ(-30%)',
  'transform: translateZ(-40%)',
  'transform: translateZ(-50%)'
]
for (var i = 0; i <= propertiesTransform.length; i++) {
    if (document.querySelector(`.${propertiesTransform[i]}`) && !document.querySelector('style').innerText.includes(propertiesTransform[i])) {
        let styles = ` 
            .${propertiesTransform[i]} { 
                ${valuesTransform[i]}
            }`;
        document.getElementsByTagName('style')[0].appendChild(document.createTextNode(styles));
    }
}