let propertiesWidthHeight = [
    'v-w-1',
    'v-w-1-5',
    'v-w-2',
    'v-w-2-5',
    'v-w-3',
    'v-w-3-5',
    'v-w-4',
    'v-w-4-5',
    'v-w-5',
    'v-w-5-5',
    'v-w-6',
    'v-w-6-5',
    'v-w-7',
    'v-w-7-5',
    'v-w-8',
    'v-w-8-5',
    'v-w-9',
    'v-w-9-5',
    'v-w-full',
    'v-w-screen',
    'v-w-min',
    'v-w-max',
    'v-w-half',
    'v-w-5px',
    'v-w-10px',
    'v-w-15px',
    'v-w-20px',
    'v-w-25px',
    'v-w-30px',
    'v-w-35px',
    'v-w-40px',
    'v-w-45px',
    'v-w-50px',
    'v-w-55px',
    'v-w-60px',
    'v-w-65px',
    'v-w-70px',
    'v-w-75px',
    'v-w-80px',
    'v-w-85px',
    'v-w-90px',
    'v-w-95px',
    'v-w-100px',
    'v-w-200px',
    'v-w-300px',
    'v-w-400px',
    'v-w-500px',
    'v-w-600px',
    'v-w-700px',
    'v-w-800px',  
    'v-h-1',
    'v-h-1-5',
    'v-h-2',
    'v-h-2-5',
    'v-h-3',
    'v-h-3-5',
    'v-h-4',
    'v-h-4-5',
    'v-h-5',
    'v-h-5-5',
    'v-h-6',
    'v-h-6-5',
    'v-h-7',
    'v-h-7-5',
    'v-h-8',
    'v-h-8-5',
    'v-h-9',
    'v-h-9-5',
    'v-h-full',
    'v-h-screen',
    'v-h-min',
    'v-h-max',
    'v-h-half',
    'v-h-5px',
    'v-h-10px',
    'v-h-15px',
    'v-h-20px',
    'v-h-25px',
    'v-h-30px',
    'v-h-35px',
    'v-h-40px',
    'v-h-45px',
    'v-h-50px',
    'v-h-55px',
    'v-h-60px',
    'v-h-65px',
    'v-h-70px',
    'v-h-75px',
    'v-h-80px',
    'v-h-85px',
    'v-h-90px',
    'v-h-95px',
    'v-h-100px',
    'v-h-200px',
    'v-h-300px',
    'v-h-400px',
    'v-h-500px',
    'v-h-600px',
    'v-h-700px',
    'v-h-800px',
]

let valuesWidthHeight = [
    'width: 10%;',
    'width: 15%;',
    'width: 20%;',
    'width: 25%;',
    'width: 30%;',
    'width: 35%;',
    'width: 40%;',
    'width: 45%;',
    'width: 50%;',
    'width: 55%;',
    'width: 60%;',
    'width: 65%;',
    'width: 70%;',
    'width: 75%;',
    'width: 80%;',
    'width: 85%;',
    'width: 90%;',
    'width: 95%;',
    'width: 100%;',
    'width: 100vw;',
    'width: min-content;',
    'width: max-content;',
    'width: 50%;',
    'width: 5px;',
    'width: 10px;',
    'width: 15px;',
    'width: 20px;',
    'width: 25px;',
    'width: 30px;',
    'width: 35px;',
    'width: 40px;',
    'width: 45px;',
    'width: 50px;',
    'width: 55px;',
    'width: 60px;',
    'width: 65px;',
    'width: 70px;',
    'width: 75px;',
    'width: 80px;',
    'width: 85px;',
    'width: 90px;',
    'width: 95px;',
    'width: 100px;',
    'width: 200px;',
    'width: 300px;',
    'width: 400px;',
    'width: 500px;',
    'width: 600px;',
    'width: 700px;',
    'width: 800px;',
    'height: 10%;',
    'height: 15%;',
    'height: 20%;',
    'height: 25%;',
    'height: 30%;',
    'height: 35%;',
    'height: 40%;',
    'height: 45%;',
    'height: 50%;',
    'height: 55%;',
    'height: 60%;',
    'height: 65%;',
    'height: 70%;',
    'height: 75%;',
    'height: 80%;',
    'height: 85%;',
    'height: 90%;',
    'height: 95%;',
    'height: 100%;',
    'height: 100vw;',
    'height: min-content;',
    'height: max-content;',
    'height: 50%;',
    'height: 5px;',
    'height: 10px;',
    'height: 15px;',
    'height: 20px;',
    'height: 25px;',
    'height: 30px;',
    'height: 35px;',
    'height: 40px;',
    'height: 45px;',
    'height: 50px;',
    'height: 55px;',
    'height: 60px;',
    'height: 65px;',
    'height: 70px;',
    'height: 75px;',
    'height: 80px;',
    'height: 85px;',
    'height: 90px;',
    'height: 95px;',
    'height: 100px;',
    'height: 200px;',
    'height: 300px;',
    'height: 400px;',
    'height: 500px;',
    'height: 600px;',
    'height: 700px;',
    'height: 800px;',
]

for (var i = 0; i <= propertiesWidthHeight.length; i++) {
    if (document.querySelector(`.${propertiesWidthHeight[i]}`) && !document.querySelector('style').innerText.includes(propertiesWidthHeight[i])) {
        let styles = ` 
        @media screen and (min-width: 900px){
            .${propertiesWidthHeight[i]} { 
                ${valuesWidthHeight[i]}
            }
        }`;
        document.getElementsByTagName('style')[0].appendChild(document.createTextNode(styles));
    }
}
